# Generated by Django 4.2.6 on 2023-10-17 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestres',
            field=models.ManyToManyField(null=True, to='app.semestre'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='disciplinas',
            field=models.ManyToManyField(null=True, to='app.disciplina'),
        ),
    ]
