# Generated by Django 4.2.6 on 2023-10-17 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_aluno_curso_alter_curso_semestres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('D', 'Diurno'), ('N', 'Noturno')], max_length=1),
        ),
    ]
