# Generated by Django 4.2.6 on 2023-10-22 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_disciplina_requisito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='requisito',
            field=models.ManyToManyField(blank=True, to='app.disciplina'),
        ),
    ]
